server:
  port: 8080
spring:
  profiles:
    active: dev
  redis:
    host: 192.168.1.105
    database: 10
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 2
        max-wait: -1
  application:
    name: miaosha-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.105:8848

#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false


mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.farmer.miaosha.dao
logging:
  level:
    com.farmer.miaosha.dao: debug
